In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("cars.csv")
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [3]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [4]:
df['brand'].nunique()

32

In [5]:
# One Hot Encoding using pandas
df_encoded = pd.get_dummies(df, columns=['fuel','owner'], drop_first=True)

In [6]:
df_encoded.head()

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False

# One Hot Encoding using Scikit-Learn

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(df.drop('selling_price',axis=1), 
                                                   df['selling_price'], 
                                                   test_size=0.2, 
                                                   random_state=42 )

In [8]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [9]:
X_train

         brand  km_driven    fuel                 owner
6518      Tata       2560  Petrol           First Owner
6144     Honda      80000  Petrol          Second Owner
6381   Hyundai     150000  Diesel  Fourth & Above Owner
438     Maruti     120000  Diesel          Second Owner
5939    Maruti      25000  Petrol           First Owner
...        ...        ...     ...                   ...
5226  Mahindra     120000  Diesel           First Owner
5390    Maruti      80000  Diesel          Second Owner
860    Hyundai      35000  Petrol           First Owner
7603    Maruti      27000  Diesel           First Owner
7270    Maruti      70000  Petrol          Second Owner

[6502 rows x 4 columns]

In [10]:
from sklearn.preprocessing import OneHotEncoder

# ohe = OneHotEncoder(drop = 'first', sparse=False)
# X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

ohe = OneHotEncoder(drop = 'first', dtype=np.int32)
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [11]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new)).shape

(6502, 9)

Columns with larger number of unique values are not suitable for One Hot Encoding. For example, the column 'brand' has 30 unique values. If we apply One Hot Encoding to this column, it will create 29 new columns (after dropping the first one). This can lead to a significant increase in the dimensionality of the dataset, which may not be desirable.

In [12]:
counts = df['brand'].value_counts()

In [13]:
df['brand'].nunique()
threshold = 100

repl = counts[counts <= threshold].index

In [15]:
pd.get_dummies(df['brand'].replace(repl,'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3709,False,False,False,False,False,False,False,False,False,True,False,False,False
3641,False,False,False,False,False,False,True,False,False,False,False,False,False
3153,False,False,False,False,False,False,False,False,False,True,False,False,False
4010,False,False,False,False,False,True,False,False,False,False,False,False,False
3404,False,False,False,False,True,False,False,False,False,False,False,False,False